
title: Cro's blog
email: email@domain.com
description: Science... Mystery... Art... Random things.

baseurl: ""
url: "http://127.0.0.1"
twitter_username: croqaz
github_username:  croqaz

permalink: pretty
markdown: kramdown
paginate: 10
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]
