
title: Cro's blog
email: cristi.constantin@live.com
description: Science... Mystery... Art... Random things.

baseurl: ""
url: "https://croqaz.github.io"
twitter_username: croqaz
github_username:  croqaz

sass:
  style: compressed

permalink: pretty
markdown: kramdown
paginate: 5
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]
