
title: Cro's blog
email: cristi.constantin@live.com
description: Science... Mystery... Art... Random things.

baseurl: ""
url: "https://croqaz.github.io"
twitter_username: croqaz
github_username:  croqaz

sass:
  style: compressed

# Build settings
permalink: /:year/:month/:title
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true

compress_html:
  blanklines: true

paginate: 9
google_analytics: 'UA-XXXXXXXX-X'

gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
exclude:
  - scripts/
  - Gemfile
  - Gemfile.lock
